import React, { Component } from "react";
import "../index.css";
import Content from "./content";

class Leaderboard extends Component {
  render() {
    //var { rank, name, kd, wr, kills, wins, matches, score } = this.props.data;

    return (
      <div>
        <table>
          <tbody>
            <tr>
              <th className="rank">Rank</th>
              <th>Name</th>
              <th>K/D</th>
              <th>WR</th>
              <th>Kills</th>
              <th>Wins</th>
              <th>Matches</th>
              <th>Score</th>
            </tr>
          </tbody>
          <tbody>
            <tr>
              <td>1</td>
              <td>Peter</td>
              <td>5.00</td>
              <td>10%</td>
              <td>42</td>
              <td>3</td>
              <td>8</td>
              <td>1,338</td>
            </tr>
          </tbody>
          <tbody>
            <tr>
              <td>2</td>
              <td>Lois</td>
              <td>7.25</td>
              <td>6%</td>
              <td>32</td>
              <td>3</td>
              <td>12</td>
              <td>1,1222</td>
            </tr>
          </tbody>
          <tbody>
            <tr>
              <td>3</td>
              <td>Cordell</td>
              <td>4.92</td>
              <td>12%</td>
              <td>38</td>
              <td>5</td>
              <td>19</td>
              <td>1,152</td>
            </tr>
          </tbody>
          <tbody>
            <tr>
              <td>4</td>
              <td>Liudmila</td>
              <td>7.63</td>
              <td>9%</td>
              <td>38</td>
              <td>3</td>
              <td>9</td>
              <td>1,110</td>
            </tr>
          </tbody>
          <tbody>
            <tr>
              <td>5</td>
              <td>Shani</td>
              <td>5.66</td>
              <td>7%</td>
              <td>25</td>
              <td>4</td>
              <td>16</td>
              <td>1,005</td>
            </tr>
          </tbody>
          <tbody>
            <tr>
              <td>6</td>
              <td>johnny</td>
              <td>5.22</td>
              <td>5%</td>
              <td>22</td>
              <td>3</td>
              <td>10</td>
              <td>956</td>
            </tr>
          </tbody>
          <tbody>
            <tr>
              <td>7</td>
              <td>jack</td>
              <td>4.33</td>
              <td>7.6%</td>
              <td>18</td>
              <td>1</td>
              <td>11</td>
              <td>872</td>
            </tr>
          </tbody>
          <tbody>
            <tr>
              <td>8</td>
              <td>Jill</td>
              <td>4.25</td>
              <td>6%</td>
              <td>9</td>
              <td>2</td>
              <td>5</td>
              <td>852</td>
            </tr>
          </tbody>
          <tbody>
            <tr>
              <td>9</td>
              <td>Hudson</td>
              <td>2.56</td>
              <td>3%</td>
              <td>6</td>
              <td>1</td>
              <td>8</td>
              <td>756</td>
            </tr>
          </tbody>
          <tbody>
            <tr>
              <td>10</td>
              <td>Hawk</td>
              <td>2.36</td>
              <td>0%</td>
              <td>4</td>
              <td>0</td>
              <td>9</td>
              <td>568</td>
            </tr>
          </tbody>
        </table>
      </div>
    );
  }
}

export default Leaderboard;
